filesystem:
  response_format: rfk
  url: http://127.0.0.1:50000
  roots:
    - /tmp
    - /var/tmp

# canvas:
#   url: canvas

# MCP configuration
mcp_config:
  type: cline
  path: /Users/gregory/Library/Application Support/Cursor/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json
