knowledge_base:
  response_format: plain
  url: http://192.168.88.210:8007


# canvas:
#   url: canvas

# MCP configuration
#mcp_config:
#  type: cline
#  path: /Users/gregory/Library/Application Support/Cursor/User/globalStorage/saoudrizwan.claude-dev/settings/cline_mcp_settings.json
